# Generated by Django 3.0.5 on 2020-04-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=255)),
                ('app_id', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('request', models.TextField(null=True)),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user_id'], name='user_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('user_id', 'app_id')},
        ),
    ]
