# Generated by Django 3.0.5 on 2020-04-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=50, null=True)),
                ('image_url', models.TextField(max_length=255, null=True)),
                ('access_token', models.TextField(null=True)),
                ('refresh_token', models.TextField(null=True)),
                ('id_token', models.TextField(null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
