# Generated by Django 3.0.5 on 2020-04-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreModule', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.CharField(default='fcf62076-d3a0-41c8-9b1a-9e369bc1b6e2', max_length=50),
        ),
    ]
