# Generated by Django 3.0.5 on 2020-04-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreModule', '0003_auto_20200428_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_id', models.CharField(max_length=255)),
                ('component_id', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('request', models.TextField(null=True)),
            ],
            options={
                'db_table': 'component',
            },
        ),
        migrations.RemoveIndex(
            model_name='application',
            name='user_idx',
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(default='29adac26-eafc-4973-af69-cbb42ce7fe10', max_length=50),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user_id'], name='user_application_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_id'], name='user_idx'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['app_id'], name='app_component_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='component',
            unique_together={('app_id', 'component_id')},
        ),
    ]
